version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0.4-sdk-2.1.3-jessie
    steps:
      - checkout
      - run:
          name: Make scripts executable
          command: |
            chmod +x build/dotnet-install.sh
            chmod +x ./build.sh
      # `dotnet-install.sh` is available at: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
      # `Cake.dll` is targeting `.NET Core` `1.0.3`, so we need to install the latest `1.0.x` runtime
      # The runtime is required to run a `.NET Core` application, it's part of the `SDK`
      # https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
      - run:
          name: Install .NET Core 1.0.8 runtime
          command: |
            echo 'export DOTNET_RUNTIME_INSTALL_DIR="$PWD/.dotnetcli"' >> $BASH_ENV
            build/dotnet-install.sh --shared-runtime --version 1.0.8 --install-dir "$PWD/.dotnetcli"
      - run:
          name: Install Mono
          command: |
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            echo "deb http://download.mono-project.com/repo/debian jessie main" | tee /etc/apt/sources.list.d/mono-official.list
            apt-get update
            apt-get -qq -y install mono-complete
      - run:
          name: Build
          command: ./build.sh --pack
      - store_artifacts:
          path: artefacts/packages
          destination: packages
      - store_artifacts:
          path: artefacts/tests-results
          destination: tests-results